# Generated by Django 3.1.12 on 2021-08-05 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_to', models.CharField(max_length=200)),
                ('receipt_id', models.CharField(max_length=30, unique=True)),
                ('payment_type', models.CharField(default='Cash', max_length=15)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=52)),
                ('payment_detail', models.TextField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
