# Generated by Django 3.1.12 on 2022-01-30 05:52

import Receipt.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_issued",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "receipt_id",
                    models.CharField(
                        db_index=True,
                        default=Receipt.models.set_receipt_id,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        default=Receipt.models.get_payment_type, max_length=15
                    ),
                ),
                ("customer_phone_number", models.CharField(max_length=15)),
                ("customer_name", models.CharField(db_index=True, max_length=100)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=52),
                ),
                ("payment_detail", models.TextField()),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
