# Generated by Django 3.1.12 on 2022-01-30 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Receipt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipthistory",
            name="date_issued",
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
